version: '3'

services:
  main:
    build: .
    image: ${APP_NAME}
    command: bash -c 'npm install && npm test'
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ../tools:/app/tools
