version: '3'

services:
  infra:
    build: .
    image: infra
    platform: linux/amd64
    env_file: .env
    command: bash /app/infra/run.sh
    ports:
      - 8001:8001
    volumes:
      - $PROJECT_DIR:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kind

networks:
  kind:
    name: kind
