version: '3'

services:
  main:
    depends_on:
      - kind-registry
    build: .
    image: infra
    platform: linux/amd64
    environment:
      PULUMI_CONFIG_PASSPHRASE: infra
    command: bash /app/infra/run.sh
    ports:
      - 8001:8001
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kind
  kind-registry:
    container_name: kind-registry
    image: registry:2
    ports:
      - 5000:5000
    networks:
      - kind

networks:
  kind:
    name: kind
