version: '3'

services:
  main:
    build: .
    image: ${APP_NAME}
    platform: linux/amd64
    environment:
      PULUMI_CONFIG_PASSPHRASE: infra
    command: bash /app/infra/run.sh
    ports:
      - 8001:8001
    volumes:
      - ../:/app
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kind

networks:
  kind:
    name: kind
