version: '3'

services:
  main:
    depends_on:
      - postgres
    build: .
    image: ${APP_NAME}
    environment:
      IS_DEVELOPMENT: 'true'
      POSTGRES_DB: test-db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    command: >
      bash -c '
        tools/wait-for-it.sh postgres:5432 -t 60 &&
        pytest -s -vv --mocha &&
        watchmedo shell-command \
          --command="pytest -s -vv --mocha" \
          --patterns="*.json;*.py;*.sh;*.txt;*.yaml;" \
          --recursive \
          /app
      '
    ports:
      - 8080:8080
    volumes:
      - ./:/app
      - ../python-lib:/app/lib
      - ../tools:/app/tools
  postgres:
    image: postgres:9.6.11-alpine
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    ports:
      - 5432:5432
